#!/bin/bash
# g26 - ssh helper for vm-t5run5 (port 10026)
exec ssh -i /home/ppw/vm/trixie.id_rsa -p 10026 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR root@127.0.0.1 "$@"
